/**
 * @swg/game-logic
 * Game logic utilities and constants for SWG server
 */

export * from './movement/index.js';
export * from './creatures/index.js';
export * from './progression/index.js';

// Combat re-exports (rename collisions with progression and space-combat)
export {
  // combat-states
  CombatState,
  type CombatStateEffect,
  type StateImmunity,
  CombatStateModifiers,
  StateImmunityDurations,
  canPerformAction,
  calculateCombinedModifiers,
  getCombatStateName,
  // combat-command
  TargetType,
  WeaponType as CombatWeaponType,
  CombatPosture,
  CombatDamageType,
  HamPool,
  type CombatCommand,
  type CombatCommandFlags,
  DefaultCommandFlags,
  createCombatCommand,
  calculateCommandCrc,
  isValidCombatPosture,
  getWeaponTypeName as getCombatWeaponTypeName,
  getTargetTypeName,
  isMeleeWeapon,
  isRangedWeapon,
  // command-parser
  type ParsedCommand,
  type CombatCreatureObject,
  type ValidationResult,
  ValidationErrorCode,
  validationSuccess,
  validationFailure,
  CommandRegistry,
  CombatCommandParser,
  createCombatCommandParser,
  // command-queue
  type QueuedCommand,
  type ExecutingCommand,
  type ExecutedCommand,
  CommandQueue,
  createCommandQueue,
  // cooldown-manager
  CooldownManager,
  createCooldownManager,
  // command-loader
  type RawCommandData,
  loadBuiltInCommands,
  createDefaultCommandRegistry,
  loadCustomCommands,
  getBuiltInCommandNames,
  getBuiltInCommand,
  validateCommandData,
  // damage-types
  DamageType,
  HitLocation,
  HIT_LOCATION_WEIGHTS,
  HIT_LOCATION_MODIFIERS,
  type DamageResult,
  type HealResult,
  calculateHitLocation,
  getHitLocationModifier,
  getHitLocationName,
  createEmptyDamageResult,
  createEmptyHealResult,
  // ham-modifiers
  HamModifierType,
  ModifierSource,
  type HamModifier,
  HamModifierManager,
  createFoodBuff,
  createMedicalHoT,
  createPoisonDoT,
  createDiseaseDoT,
  createBleedingDoT,
  createFireDoT,
  // regeneration
  BASE_REGEN_RATES,
  POSTURE_REGEN_MODIFIERS,
  COMBAT_REGEN_MODIFIER,
  OUT_OF_COMBAT_REGEN_MODIFIER,
  WOUND_REGEN_PENALTY_PER_POINT,
  MAX_WOUND_REGEN_PENALTY,
  BATTLE_FATIGUE_REGEN_PENALTY_PER_POINT,
  MAX_BATTLE_FATIGUE_REGEN_PENALTY,
  ENTERTAINER_REGEN_BONUS,
  CAMPFIRE_REGEN_BONUS,
  type RegenCalculation,
  type RegenerationState,
  calculateWoundPenalty,
  calculateBattleFatiguePenalty,
  calculateRegenRate,
  createRegenState,
  processRegeneration,
  updateRegenBonuses,
  pauseRegeneration,
  resumeRegeneration,
  getTimeToFullRegen,
  // incapacitation
  IncapConfig,
  DeathType,
  type IncapRecord,
  type DeathRecord,
  type IncapacitationState,
  type IncapCheckResult,
  type DeathResult,
  createIncapState,
  cleanupIncapRecords,
  checkIncapacitation,
  applyIncapacitation,
  isIncapTimerExpired,
  reviveFromIncap,
  applyDeathblow,
  calculateXpLoss,
  processDeath,
  cloneCreature,
  setCloneLocation,
  hasCloneSickness,
  getCloneSicknessRemaining,
  processIncapTick,
  canBeDeathBlown,
  // ham-manager
  type HamManagerConfig,
  DEFAULT_HAM_CONFIG,
  HamManager,
  createHamManager,
  // combat-manager
  type CombatResult,
  type DamageCalculation,
  type HitResult,
  type MitigationResult,
  type CombatSpamMessage,
  type AoeTarget,
  type CombatManagerConfig,
  DEFAULT_COMBAT_CONFIG,
  POSTURE_DEFENSE_MODIFIERS,
  CombatManager,
  createCombatManager,
} from './combat/index.js';

// Skills re-exports (rename collisions with progression)
export {
  XpType as SkillXpType,
  type SkillTemplate as SkillsSkillTemplate,
  type SkillTemplateData,
  type SkillTreeNode,
  convertToSkillTemplate,
  convertToSkillTemplateData,
  isNoviceSkill,
  canSpeciesLearnSkill,
  getSkillModValue,
  skillGrantsCommand,
  skillGrantsCertification,
} from './skills/skill-template.js';
export * from './skills/skill-mods.js';
export * from './skills/skill-loader.js';
export * from './skills/professions.js';
export * from './skills/skill-manager.js';

export * from './crafting/index.js';
export * from './resources/index.js';
export * from './equipment/index.js';
export * from './survey/index.js';
export * from './mail/index.js';

// Quests re-exports (rename collisions with pvp)
export {
  // quest-types
  QuestType,
  QuestStatus,
  ObjectiveType as QuestObjectiveType,
  QuestRewardType,
  QuestPrerequisiteType,
  QuestResultCode,
  type QuestLocation,
  type QuestObjective,
  type QuestReward,
  type QuestPrerequisite,
  type Quest,
  type ThemeParkQuest,
  type ThemeParkChain,
  type QuestData,
  type QuestObjectiveData,
  type QuestRewardData,
  type QuestPrerequisiteData,
  type ThemeParkChainData,
  isThemeParkQuest,
  isValidQuestType,
  isValidObjectiveType,
  isValidRewardType,
  isValidPrerequisiteType,
  // quest-loader
  QuestLoader,
  QuestLoadError,
  QuestValidationError,
  type QuestLoadResult,
  type BulkLoadResult as QuestBulkLoadResult,
  getQuestLoader,
  createQuestLoader,
  loadQuests,
  getQuest,
  getQuestsByType,
  getQuestChain,
  // quest-journal
  QuestJournal,
  type ObjectiveProgress,
  type ActiveQuest,
  type CompletedQuestRecord,
  type QuestJournalData,
  type JournalOperationResult,
  type PlayerPrerequisites,
  type QuestJournalEvent,
  type QuestJournalEventListener,
  createQuestJournal,
  restoreQuestJournal,
  // mission-terminal-types
  MissionTerminalType,
  MissionDifficulty,
  GeneratedMissionType,
  type MissionLocation,
  type MissionTarget,
  type DeliveryItem,
  type GeneratedMission,
  type MissionGenerationParams,
  type MissionTerminalConfig,
  type LairSpawnConfig,
  type BountyTargetConfig,
  DEFAULT_TERMINAL_CONFIGS,
  DIFFICULTY_CREDIT_MULTIPLIERS,
  BASE_CREDIT_REWARDS,
  LEVEL_CREDIT_SCALING,
  validateGenerationParams,
  calculateCreditReward,
  determineDifficulty,
  generateMissionId,
  isValidTerminalType,
  isValidDifficulty,
  isValidMissionType,
} from './quests/index.js';

export * from './jedi/index.js';
export * from './bounty/index.js';

// Faction re-exports (rename collisions with pvp)
export {
  // faction-types
  Faction,
  FactionStatus,
  GCWRegionStatus,
  FactionRankType,
  FactionPerkEffectType,
  GCWContributionSource,
  FACTION_LEAVE_COOLDOWN_MS,
  STATUS_CHANGE_COOLDOWN_MS,
  SF_LEAVE_COOLDOWN_MS,
  MAX_FACTION_POINTS,
  MIN_FACTION_POINTS,
  POINTS_LOST_ON_DEATH,
  WEEKLY_CONTROL_DECAY_PERCENT,
  DEFAULT_NPC_KILL_POINTS,
  DEFAULT_PLAYER_KILL_POINTS,
  IMPERIAL_RANKS,
  REBEL_RANKS,
  type FactionRank,
  type FactionStanding,
  type GCWRegion,
  type FactionPerk,
  type FactionBase,
  type FactionNPCTemplate,
  type PlayerFactionData,
  type GCWContribution,
  type ImperialRankIndex,
  type RebelRankIndex,
  isGCWFaction,
  getOpposingFaction,
  getRanksForFaction,
  getRankByPoints,
  getFactionName,
  getStatusName,
  canAttack,
  calculateControlPercentage,
  createDefaultFactionData,
  createDefaultStanding,
  // faction-manager
  FactionManager,
  createFactionManager,
  DEFAULT_FACTION_CONFIG,
  type FactionManagerConfig,
  type FactionOperationResult,
  type EnlistResult,
  type StatusChangeResult,
  type PointChangeResult,
  type PerkPurchaseResult,
  type FactionStatusChangedEvent,
  type FactionRankChangedEvent,
  type FactionPointsChangedEvent,
  type FactionEnlistedEvent,
  type FactionResignedEvent,
  type FactionStatusChangedHandler,
  type FactionRankChangedHandler,
  type FactionPointsChangedHandler,
  type FactionEnlistedHandler,
  type FactionResignedHandler,
  type FactionRepository,
  // gcw-manager
  GCWManager,
  createGCWManager,
  DEFAULT_GCW_CONFIG,
  CONTROL_THRESHOLD_PERCENT,
  CONTESTED_FLIP_THRESHOLD,
  BASE_PASSIVE_CONTRIBUTION,
  BASE_DESTRUCTION_POINTS,
  BASE_DEFENSE_POINTS,
  BASE_VULNERABILITY_HOURS,
  PASSIVE_TICK_INTERVAL_MS,
  MAX_BASES_PER_REGION,
  type GCWManagerConfig,
  type GCWOperationResult,
  type ContributionResult,
  type BasePlacementResult,
  type BaseDestructionResult,
  type RegionalBonus,
  type RegionControlChangedEvent,
  type BasePlacedEvent,
  type BaseDestroyedEvent,
  type GCWPointsContributedEvent,
  type RegionControlChangedHandler,
  type BasePlacedHandler,
  type BaseDestroyedHandler,
  type GCWPointsContributedHandler,
  type GCWRepository,
  // faction-rewards (rename OBJECTIVE_CAPTURE_POINTS collision with invasion-event)
  FactionRewardManager,
  createFactionRewardManager,
  DEFAULT_REWARD_CONFIG as DEFAULT_FACTION_REWARD_CONFIG,
  MISSION_BASE_POINTS,
  MISSION_DIFFICULTY_BONUS,
  OBJECTIVE_CAPTURE_POINTS as FACTION_OBJECTIVE_CAPTURE_POINTS,
  KILL_STREAK_MULTIPLIER,
  MAX_KILL_STREAK_BONUS,
  SAME_PLAYER_KILL_COOLDOWN_MS,
  MAX_SAME_PLAYER_KILLS_PER_HOUR,
  FactionItemCategory,
  type FactionRewardConfig,
  type RewardResult,
  type RewardModifier,
  type FactionItem,
  type FactionVendorInventory,
  type RewardGrantedEvent,
  type FactionItemPurchasedEvent,
  type RewardGrantedHandler,
  type FactionItemPurchasedHandler,
  type FactionRewardRepository,
  // faction-messages
  FactionMessageOpcode,
  type FactionMessageOpcodeType,
  type FactionStatusUpdateMessage,
  type FactionPointGainMessage,
  type FactionPointLossMessage,
  type FactionRankChangeMessage,
  type GCWRegionStatusMessage,
  type GCWRegionControlChangeMessage,
  type FactionBaseStatusMessage,
  type FactionBasePlacedMessage,
  type FactionBaseDestroyedMessage,
  type FactionBaseUnderAttackMessage,
  type EnlistRequestMessage,
  type ResignRequestMessage,
  type StatusChangeRequestMessage,
  type FactionStandingRequestMessage,
  type GCWRegionInfoRequestMessage,
  type FactionPerksRequestMessage,
  type PerkPurchaseRequestMessage,
  type FactionItemsRequestMessage,
  type ItemPurchaseRequestMessage,
  type EnlistResponseMessage,
  type ResignResponseMessage,
  type StatusChangeResponseMessage,
  type FactionStandingResponseMessage,
  type GCWRegionInfoResponseMessage,
  type FactionPerksResponseMessage,
  type PerkPurchaseResponseMessage,
  type FactionItemsResponseMessage,
  type ItemPurchaseResponseMessage,
  type FactionStandingData,
  type FactionPerkData,
  type FactionItemData,
  type FactionClientMessage,
  type FactionServerMessage,
  type FactionMessage,
  isFactionMessageOpcode,
  createFactionStatusUpdate,
  createFactionPointGain,
  createFactionPointLoss,
  createFactionRankChange,
  createGCWRegionStatus,
  createGCWRegionControlChange,
  createFactionBaseStatus,
  createFactionBasePlaced,
  createFactionBaseDestroyed,
  createFactionBaseUnderAttack,
  createEnlistResponse,
  createResignResponse,
  createStatusChangeResponse,
  getRegionStatusName,
  // gcw-mechanics
  GCWMechanics,
  createGCWMechanics,
  DEFAULT_MECHANICS_CONFIG,
  MIN_DISTANCE_FROM_CITY,
  MIN_DISTANCE_BETWEEN_BASES,
  MIN_DISTANCE_FROM_ENEMY_BASE,
  DEFAULT_BASE_HEALTH,
  DEFENSE_RATING_DAMAGE_REDUCTION,
  MAX_DEFENSE_RATING,
  INVASION_TRIGGER_THRESHOLD,
  INVASION_CONTROL_CHANGE_THRESHOLD,
  WEEKLY_POINT_DECAY_PERCENT,
  TOP_CONTRIBUTOR_BONUS,
  WEEKLY_CYCLE_MS,
  ZONE_BONUS_TIERS,
  type GCWMechanicsConfig,
  type BasePlacementValidation,
  type BaseDefenses,
  type ZoneBonuses,
  type WeeklyCycleRewards,
  type CityLocation,
  type InvasionStartedEvent,
  type WeeklyCycleResetEvent,
  type BaseVulnerabilityChangedEvent,
  type InvasionStartedHandler,
  type WeeklyCycleResetHandler,
  type BaseVulnerabilityChangedHandler,
  // invasion-event
  InvasionEvent,
  createInvasionEvent,
  DEFAULT_INVASION_CONFIG,
  InvasionPhase,
  InvasionObjectiveType,
  ObjectiveStatus,
  MUSTERING_DURATION_MS,
  ASSAULT_DURATION_MS,
  DEFENSE_DURATION_MS,
  RESOLUTION_DURATION_MS,
  MIN_PARTICIPANTS,
  OBJECTIVE_CAPTURE_POINTS as INVASION_OBJECTIVE_CAPTURE_POINTS,
  OBJECTIVE_DEFEND_POINTS,
  PLAYER_KILL_POINTS,
  NPC_KILL_POINTS,
  VICTORY_BONUS_POINTS,
  BASE_REWARD_MULTIPLIER,
  MAX_REWARD_MULTIPLIER,
  type InvasionConfig,
  type InvasionObjective,
  type InvasionParticipant,
  type InvasionResult,
  type ParticipantReward,
  type PhaseChangeHandler,
  type ObjectiveUpdateHandler,
  type ParticipantJoinHandler,
  type ParticipantLeaveHandler,
  type ScoreUpdateHandler,
  type CompleteHandler,
  // faction-npc-spawner
  FactionNPCSpawner,
  createFactionNPCSpawner,
  DEFAULT_SPAWNER_CONFIG,
  NPCSpawnTier,
  NPCRole,
  NPCBehavior,
  TIER_BASE_SPAWN_COUNT,
  TIER_CONTROL_THRESHOLD,
  REINFORCEMENT_DELAY_MS,
  MAX_REINFORCEMENT_WAVES,
  NPC_RESPAWN_DELAY_MS,
  PATROL_UPDATE_INTERVAL_MS,
  MAX_PATROL_WAYPOINTS,
  MAX_NPCS_PER_REGION,
  IMPERIAL_TEMPLATES,
  REBEL_TEMPLATES,
  type NPCSpawnerConfig,
  type PatrolWaypoint,
  type PatrolRoute,
  type SpawnPoint as FactionSpawnPoint,
  type ReinforcementRequest,
  type SpawnedNPC,
  type NPCSpawnedEvent,
  type NPCDespawnedEvent,
  type ReinforcementsCalledEvent,
  type NPCSpawnedHandler,
  type NPCDespawnedHandler,
  type ReinforcementsCalledHandler,
  // gcw-messages
  GCWMessageOpcode,
  type GCWMessageOpcodeType,
  type InvasionStartMessage,
  type InvasionPhaseChangeMessage,
  type InvasionObjectiveMessage,
  type InvasionResultMessage,
  type InvasionParticipantUpdateMessage,
  type InvasionScoreUpdateMessage,
  type InvasionJoinRequestMessage,
  type InvasionJoinResponseMessage,
  type InvasionLeaveRequestMessage,
  type InvasionRewardsMessage,
  type BaseVulnerabilityMessage,
  type BaseDamageMessage,
  type BaseDefensesMessage,
  type SetVulnerabilityRequestMessage,
  type SetVulnerabilityResponseMessage,
  type WeeklyCycleResetMessage,
  type WeeklyCycleRewardsMessage,
  type WeeklyDecayAppliedMessage,
  type ZoneBonusesMessage,
  type ZoneBonusesRequestMessage,
  type FactionNPCsSpawnedMessage,
  type ReinforcementsArrivingMessage,
  type InvasionObjectiveData,
  type InvasionParticipantData,
  type SpawnedNPCData,
  type GCWClientMessage,
  type GCWServerMessage,
  type GCWMessage,
  isGCWMessageOpcode,
  objectiveToData,
  participantToData,
  spawnedNPCToData,
  createInvasionStartMessage,
  createInvasionPhaseChangeMessage,
  createInvasionObjectiveMessage,
  createInvasionResultMessage,
  createBaseVulnerabilityMessage,
  createWeeklyCycleResetMessage,
  createZoneBonusesMessage,
  createFactionNPCsSpawnedMessage,
  createReinforcementsArrivingMessage,
} from './faction/index.js';

// Space combat re-exports (rename collisions with combat)
export {
  WeaponType as SpaceWeaponType,
  TargetLockState,
  DamageType as SpaceDamageType,
  ShipHitLocation,
  type CombatResult as SpaceCombatResult,
  type ComponentDamageResult,
  type ProjectileState,
  type MissileState,
  type CountermeasureState,
  type TargetLockInfo,
  type SpaceWeaponStats,
  type SpaceCombatConfig,
  type ShipCombatStats,
  DEFAULT_SPACE_COMBAT_CONFIG,
  createEmptyCombatResult,
  createProjectileState,
  createMissileState,
  createCountermeasureState,
  createTargetLockInfo,
  createDefaultWeaponStats,
  isMissileState,
  isGuidedWeapon,
  weaponRequiresAmmo,
  getWeaponTypeName as getSpaceWeaponTypeName,
  getDamageTypeName,
  getTargetLockStateName,
  calculateHitLocation as calculateSpaceHitLocation,
  distance3D,
  normalizeVector,
  dotProduct,
  // space-combat-manager
  type WeaponFireResult,
  type ShipDestructionEvent,
  type ShipDestructionCallback,
  type ProjectileHitCallback,
  SpaceCombatManager,
  createSpaceCombatManager,
  // turret-controller
  type TurretArc,
  type TurretConfig,
  type TurretState,
  type TurretFireResult,
  DEFAULT_TURRET_ARCS,
  TurretController,
  createTurretController,
  createTurretConfig,
  createYT1300TurretConfigs,
  createARC170TurretConfigs,
  // space-combat-messages
  SpaceCombatMessageOpcode,
  type SpaceCombatMessageOpcodeType,
  ProjectileDespawnReason,
  ShipDestructionReason,
  type WeaponFireMessage,
  type MissileLaunchMessage,
  type CountermeasureDeployMessage,
  type TargetLockRequestMessage,
  type TurretFireMessage,
  type WeaponFireResponseMessage,
  type ProjectileSpawnMessage,
  type ProjectileUpdateMessage,
  type ProjectileDespawnMessage,
  type MissileTrackingMessage,
  type MissileLockWarningMessage,
  type CountermeasureDeployResponseMessage,
  type CountermeasureActiveMessage,
  type TargetLockMessage,
  type ShipHitMessage,
  type CriticalHitMessage,
  type ComponentDamageMessage,
  type ShipDestructionMessage,
  type ShipDamageUpdateMessage,
  type TurretStatusMessage,
  type SpaceCombatClientMessage,
  type SpaceCombatServerMessage,
  type SpaceCombatMessage,
  isSpaceCombatMessageOpcode,
  createWeaponFireResponse,
  createProjectileSpawnMessage,
  createMissileTrackingMessage,
  createMissileLockWarning,
  createTargetLockMessage,
  createShipHitMessage,
  createCriticalHitMessage,
  createComponentDamageMessage,
  createShipDestructionMessage,
  createShipDamageUpdateMessage,
  createTurretStatusMessage,
  getWeaponTypeDisplayName,
  getHitLocationDisplayName,
  getDestructionReasonDisplayName,
} from './space-combat/index.js';

export * from './pvp/index.js';
