/**
 * Equipment Manager
 * Handles equipping, unequipping, and managing character equipment
 */

import type { ObjectId } from '@swg/shared-types';
import type { TangibleObject, WeaponObject, ArmorObject } from '@swg/objects';
import { ObjectType } from '@swg/objects';

import {
  EquipmentSlot,
  type EquipmentSlotType,
  type EquippedItem,
  WeaponSlot,
  isWeaponSlot,
  isArmorSlot,
  isJewelrySlot,
  isSpecialSlot,
  getPairedSlot,
  getSlotDisplayName,
} from './equipment-slots.js';

import {
  type SlotRequirement,
  type RequirementCheckResult,
  type ItemEquipmentRequirement,
  EquipmentFailureReason,
  type EquipmentFailureReasonType,
  getSlotRequirements,
  validateSlotRequirements,
  validateItemRequirements,
  isSlotUnlocked,
  getFailureMessage,
} from './slot-requirements.js';

import {
  type ItemEquippedEvent,
  type ItemUnequippedEvent,
  type WeaponChangedEvent,
  createItemEquippedEvent,
  createItemUnequippedEvent,
  createWeaponChangedEvent,
} from './equipment-events.js';

/**
 * Equipment change result
 */
export interface EquipmentResult {
  /** Whether the operation succeeded */
  success: boolean;
  /** Failure reason if unsuccessful */
  reason?: EquipmentFailureReasonType;
  /** Human-readable message */
  message?: string;
  /** Previous item that was unequipped (if any) */
  previousItem?: ObjectId;
  /** Events generated by this operation */
  events: (ItemEquippedEvent | ItemUnequippedEvent | WeaponChangedEvent)[];
}

/**
 * Player context for equipment operations
 */
export interface PlayerEquipmentContext {
  /** Player's object ID */
  playerId: ObjectId;
  /** Player's species */
  species: number;
  /** Player's gender */
  gender: number;
  /** Player's level */
  level: number;
  /** Player's faction CRC */
  faction: number;
  /** Player's skills */
  skills: Set<string>;
  /** Whether player is in combat */
  inCombat: boolean;
  /** Whether player is incapacitated */
  incapacitated: boolean;
  /** Whether player is dead */
  isDead: boolean;
}

/**
 * Item context for equipment operations
 */
export interface ItemEquipmentContext {
  /** Item's object ID */
  itemId: ObjectId;
  /** Item's object type */
  objectType: ObjectType;
  /** Item's template CRC */
  templateCrc: number;
  /** Item's condition (0-100) */
  condition: number;
  /** Item's requirements */
  requirements?: ItemEquipmentRequirement;
  /** Allowed equipment slots for this item */
  allowedSlots?: EquipmentSlotType[];
  /** Whether item is a two-handed weapon */
  twoHanded?: boolean;
}

/**
 * Equipment Manager class
 * Manages a character's equipped items
 */
export class EquipmentManager {
  /** Map of equipped items by slot */
  private equippedItems: Map<EquipmentSlotType, ObjectId>;

  /** Current active weapon slot */
  private activeWeaponSlot: EquipmentSlotType;

  /** Item lookup function (to get item details) */
  private itemLookup: ((itemId: ObjectId) => TangibleObject | undefined) | null;

  /**
   * Create a new EquipmentManager
   * @param itemLookup - Optional function to look up item details by ID
   */
  constructor(itemLookup?: (itemId: ObjectId) => TangibleObject | undefined) {
    this.equippedItems = new Map();
    this.activeWeaponSlot = WeaponSlot.PRIMARY;
    this.itemLookup = itemLookup ?? null;
  }

  /**
   * Set the item lookup function
   */
  setItemLookup(lookup: (itemId: ObjectId) => TangibleObject | undefined): void {
    this.itemLookup = lookup;
  }

  /**
   * Check if a player can equip an item in a slot
   */
  canEquip(
    player: PlayerEquipmentContext,
    item: ItemEquipmentContext,
    slot: EquipmentSlotType
  ): RequirementCheckResult {
    // Check player state
    if (player.isDead) {
      return {
        allowed: false,
        reason: EquipmentFailureReason.DEAD,
        message: getFailureMessage(EquipmentFailureReason.DEAD),
      };
    }

    if (player.incapacitated) {
      return {
        allowed: false,
        reason: EquipmentFailureReason.INCAPACITATED,
        message: getFailureMessage(EquipmentFailureReason.INCAPACITATED),
      };
    }

    // Check combat restrictions for non-weapon equipment
    if (player.inCombat && !isWeaponSlot(slot)) {
      return {
        allowed: false,
        reason: EquipmentFailureReason.IN_COMBAT,
        message: getFailureMessage(EquipmentFailureReason.IN_COMBAT),
      };
    }

    // Check item condition
    if (item.condition <= 0) {
      return {
        allowed: false,
        reason: EquipmentFailureReason.CONDITION_TOO_LOW,
        message: getFailureMessage(EquipmentFailureReason.CONDITION_TOO_LOW),
      };
    }

    // Check if slot is unlocked
    if (!isSlotUnlocked(slot, player.skills)) {
      return {
        allowed: false,
        reason: EquipmentFailureReason.SLOT_LOCKED,
        message: getFailureMessage(EquipmentFailureReason.SLOT_LOCKED),
      };
    }

    // Check if item is already equipped
    for (const [equippedSlot, equippedId] of this.equippedItems) {
      if (equippedId === item.itemId) {
        return {
          allowed: false,
          reason: EquipmentFailureReason.ALREADY_EQUIPPED,
          message: getFailureMessage(EquipmentFailureReason.ALREADY_EQUIPPED),
        };
      }
    }

    // Check slot requirements
    const slotCheck = validateSlotRequirements(
      slot,
      item.objectType,
      player.species,
      player.gender,
      player.level,
      player.skills
    );

    if (!slotCheck.allowed) {
      return slotCheck;
    }

    // Check item-specific requirements
    if (item.requirements) {
      const itemCheck = validateItemRequirements(
        item.requirements,
        player.playerId,
        player.species,
        player.gender,
        player.level,
        player.faction,
        player.skills
      );

      if (!itemCheck.allowed) {
        return itemCheck;
      }
    }

    // Check if item is allowed in this specific slot
    if (item.allowedSlots && item.allowedSlots.length > 0) {
      if (!item.allowedSlots.includes(slot)) {
        return {
          allowed: false,
          reason: EquipmentFailureReason.INVALID_OBJECT_TYPE,
          message: 'This item cannot be equipped in this slot',
        };
      }
    }

    // Check two-handed weapon restrictions
    if (item.twoHanded && isWeaponSlot(slot)) {
      // Two-handed weapons require the right weapon slot and empty left slot
      if (slot !== WeaponSlot.PRIMARY) {
        return {
          allowed: false,
          reason: EquipmentFailureReason.EQUIPMENT_CONFLICT,
          message: 'Two-handed weapons must be equipped in the primary weapon slot',
        };
      }
      if (this.equippedItems.has(WeaponSlot.SECONDARY)) {
        return {
          allowed: false,
          reason: EquipmentFailureReason.EQUIPMENT_CONFLICT,
          message: 'You must unequip your secondary weapon first',
        };
      }
    }

    // Check if equipping in left weapon slot with two-handed weapon
    if (slot === WeaponSlot.SECONDARY) {
      const rightWeaponId = this.equippedItems.get(WeaponSlot.PRIMARY);
      if (rightWeaponId && this.itemLookup) {
        const rightWeapon = this.itemLookup(rightWeaponId) as WeaponObject | undefined;
        // Would need to check if right weapon is two-handed
        // For now, we'll assume the item context includes this info
      }
    }

    return { allowed: true };
  }

  /**
   * Equip an item to a slot
   */
  equip(
    player: PlayerEquipmentContext,
    item: ItemEquipmentContext,
    slot: EquipmentSlotType
  ): EquipmentResult {
    // Validate the operation
    const canEquipResult = this.canEquip(player, item, slot);
    if (!canEquipResult.allowed) {
      return {
        success: false,
        reason: canEquipResult.reason,
        message: canEquipResult.message,
        events: [],
      };
    }

    const events: (ItemEquippedEvent | ItemUnequippedEvent | WeaponChangedEvent)[] = [];
    let previousItemId: ObjectId | undefined;

    // Handle existing item in slot
    if (this.equippedItems.has(slot)) {
      previousItemId = this.equippedItems.get(slot);
      this.equippedItems.delete(slot);

      if (previousItemId) {
        events.push(
          createItemUnequippedEvent(player.playerId, previousItemId, slot)
        );
      }
    }

    // Equip the new item
    this.equippedItems.set(slot, item.itemId);

    events.push(
      createItemEquippedEvent(player.playerId, item.itemId, slot, item.templateCrc)
    );

    // Handle weapon changes
    if (isWeaponSlot(slot)) {
      const oldWeaponId = previousItemId ?? 0n;
      events.push(
        createWeaponChangedEvent(player.playerId, oldWeaponId, item.itemId, slot)
      );
    }

    return {
      success: true,
      previousItem: previousItemId,
      events,
    };
  }

  /**
   * Unequip an item from a slot
   */
  unequip(player: PlayerEquipmentContext, slot: EquipmentSlotType): EquipmentResult {
    // Check player state
    if (player.isDead) {
      return {
        success: false,
        reason: EquipmentFailureReason.DEAD,
        message: getFailureMessage(EquipmentFailureReason.DEAD),
        events: [],
      };
    }

    if (player.incapacitated) {
      return {
        success: false,
        reason: EquipmentFailureReason.INCAPACITATED,
        message: getFailureMessage(EquipmentFailureReason.INCAPACITATED),
        events: [],
      };
    }

    // Check combat restrictions for non-weapon equipment
    if (player.inCombat && !isWeaponSlot(slot)) {
      return {
        success: false,
        reason: EquipmentFailureReason.IN_COMBAT,
        message: getFailureMessage(EquipmentFailureReason.IN_COMBAT),
        events: [],
      };
    }

    // Check if slot has an item
    const itemId = this.equippedItems.get(slot);
    if (!itemId) {
      return {
        success: true,
        events: [],
      };
    }

    // Remove the item
    this.equippedItems.delete(slot);

    const events: (ItemEquippedEvent | ItemUnequippedEvent | WeaponChangedEvent)[] = [];

    events.push(createItemUnequippedEvent(player.playerId, itemId, slot));

    // Handle weapon changes
    if (isWeaponSlot(slot)) {
      events.push(createWeaponChangedEvent(player.playerId, itemId, 0n, slot));
    }

    return {
      success: true,
      previousItem: itemId,
      events,
    };
  }

  /**
   * Get the item equipped in a specific slot
   */
  getEquippedItem(slot: EquipmentSlotType): ObjectId | undefined {
    return this.equippedItems.get(slot);
  }

  /**
   * Get the currently equipped weapon
   */
  getEquippedWeapon(): ObjectId | undefined {
    return this.equippedItems.get(this.activeWeaponSlot);
  }

  /**
   * Get the active weapon slot
   */
  getActiveWeaponSlot(): EquipmentSlotType {
    return this.activeWeaponSlot;
  }

  /**
   * Swap between primary and secondary weapons
   */
  swapWeapon(playerId: ObjectId): WeaponChangedEvent | null {
    const oldSlot = this.activeWeaponSlot;
    const newSlot =
      oldSlot === WeaponSlot.PRIMARY
        ? WeaponSlot.SECONDARY
        : WeaponSlot.PRIMARY;

    // Check if the new slot has a weapon
    const newWeaponId = this.equippedItems.get(newSlot);
    if (!newWeaponId) {
      return null;
    }

    const oldWeaponId = this.equippedItems.get(oldSlot) ?? 0n;

    this.activeWeaponSlot = newSlot;

    return createWeaponChangedEvent(playerId, oldWeaponId, newWeaponId, newSlot);
  }

  /**
   * Find the best slot for an item (auto-equip)
   */
  autoEquip(
    player: PlayerEquipmentContext,
    item: ItemEquipmentContext
  ): EquipmentSlotType | null {
    // If item has preferred slots, try those first
    if (item.allowedSlots && item.allowedSlots.length > 0) {
      for (const slot of item.allowedSlots) {
        const result = this.canEquip(player, item, slot);
        if (result.allowed) {
          // Prefer empty slots
          if (!this.equippedItems.has(slot)) {
            return slot;
          }
        }
      }

      // If no empty slots, return first valid slot (will swap)
      for (const slot of item.allowedSlots) {
        const result = this.canEquip(player, item, slot);
        if (result.allowed) {
          return slot;
        }
      }
    }

    // Try to determine slot from object type
    const slotsToTry = this.getSlotsForObjectType(item.objectType);

    for (const slot of slotsToTry) {
      const result = this.canEquip(player, item, slot);
      if (result.allowed && !this.equippedItems.has(slot)) {
        return slot;
      }
    }

    // If no empty slots, return first valid slot
    for (const slot of slotsToTry) {
      const result = this.canEquip(player, item, slot);
      if (result.allowed) {
        return slot;
      }
    }

    return null;
  }

  /**
   * Get all equipped items
   */
  getAllEquippedItems(): Map<EquipmentSlotType, ObjectId> {
    return new Map(this.equippedItems);
  }

  /**
   * Get equipped items as an array
   */
  getEquippedItemsArray(): EquippedItem[] {
    const items: EquippedItem[] = [];

    for (const [slot, itemId] of this.equippedItems) {
      const item: EquippedItem = {
        objectId: itemId,
        slot,
        templateCrc: 0, // Would need to look up from item
      };

      if (this.itemLookup) {
        const tangible = this.itemLookup(itemId);
        if (tangible) {
          item.templateCrc = tangible.templateCrc;
          if (tangible.appearanceData?.length) {
            item.appearanceData = tangible.appearanceData;
          }
        }
      }

      items.push(item);
    }

    return items;
  }

  /**
   * Check if a slot has an item equipped
   */
  hasEquippedItem(slot: EquipmentSlotType): boolean {
    return this.equippedItems.has(slot);
  }

  /**
   * Check if an item is equipped (in any slot)
   */
  isItemEquipped(itemId: ObjectId): boolean {
    for (const equippedId of this.equippedItems.values()) {
      if (equippedId === itemId) {
        return true;
      }
    }
    return false;
  }

  /**
   * Find which slot an item is equipped in
   */
  findItemSlot(itemId: ObjectId): EquipmentSlotType | null {
    for (const [slot, equippedId] of this.equippedItems) {
      if (equippedId === itemId) {
        return slot;
      }
    }
    return null;
  }

  /**
   * Clear all equipped items
   */
  clearAll(): void {
    this.equippedItems.clear();
    this.activeWeaponSlot = WeaponSlot.PRIMARY;
  }

  /**
   * Load equipment state from a map
   */
  loadFromMap(items: Map<EquipmentSlotType, ObjectId>): void {
    this.equippedItems = new Map(items);
  }

  /**
   * Get possible slots for an object type
   */
  private getSlotsForObjectType(objectType: ObjectType): EquipmentSlotType[] {
    switch (objectType) {
      case ObjectType.Weapon:
        return [WeaponSlot.PRIMARY, WeaponSlot.SECONDARY];

      case ObjectType.Armor:
        return [
          EquipmentSlot.HEAD,
          EquipmentSlot.CHEST,
          EquipmentSlot.LEFT_ARM,
          EquipmentSlot.RIGHT_ARM,
          EquipmentSlot.LEFT_BICEP,
          EquipmentSlot.RIGHT_BICEP,
          EquipmentSlot.LEFT_HAND,
          EquipmentSlot.RIGHT_HAND,
          EquipmentSlot.LEGS,
          EquipmentSlot.LEFT_FOOT,
          EquipmentSlot.RIGHT_FOOT,
        ];

      case ObjectType.Tangible:
      default:
        return [
          EquipmentSlot.HEAD,
          EquipmentSlot.CHEST,
          EquipmentSlot.BACK,
          EquipmentSlot.CLOAK,
          EquipmentSlot.LEFT_HAND,
          EquipmentSlot.RIGHT_HAND,
          EquipmentSlot.BELT,
          EquipmentSlot.LEGS,
          EquipmentSlot.LEFT_FOOT,
          EquipmentSlot.RIGHT_FOOT,
          EquipmentSlot.NECKLACE,
          EquipmentSlot.LEFT_EARRING,
          EquipmentSlot.RIGHT_EARRING,
          EquipmentSlot.LEFT_RING,
          EquipmentSlot.RIGHT_RING,
        ];
    }
  }
}

/**
 * Create a new EquipmentManager instance
 */
export function createEquipmentManager(
  itemLookup?: (itemId: ObjectId) => TangibleObject | undefined
): EquipmentManager {
  return new EquipmentManager(itemLookup);
}
